### ISSUE TITLE
In Hypothesis Testing Tutorial

### ISSUE THREAD

**Issue by hungrstrike316** [charlesfrye/AppliedStatisticsForNeuroscience#42]
Slight ambiguity on whether rejecting the null hypothesis and accepting the alternative hypothesis are the same thing.  This is either a small point or a misunderstanding on my part, but they are not the same, right?  We can not _prove_ the alt hypothesis.

**Comment by charlesfrye** [comment]
You're right, I'm being a little heretical here. I think the whole apparatus of "we can't ever accept a hypothesis as true, we can only every reject a hypothesis as false" is a little silly, and says more about the philosophy of the time it was promulgated than it does about good scientific practice.

I could do with being more careful in my use of those terms, since they do have a loaded meaning in traditional hypothesis testing ideology.

**Comment by charlesfrye** [comment]
I have added the following to the lab. Thanks @hungrstrike316!

## Aside: "Accept" vs. "Fail to Reject"

The general framework for statistical hypothesis testing was laid down in the early-to-mid 20th century, amid an acrimonious debate between R.A Fisher, who advocated for a looser, more intuitive approach that saw statistical tests as an adjunct to graphical intuition, and Jerzy Neyman and Karl Pearson, who advocated for a much stricter approach.

At this time, bringing rigor to the philosophy of science was also considered of paramount importance. One of the key concepts developed in this era was "falsifiability", due to Karl Popper. Under this view, no scientific theory or model was ever to be considered "true". It was only provisionally "not falsified yet" if no evidence contradicting it was available (and a theory was only considered scientific if it was falsifiable). This admirable level of self-doubt led to a very particular terminology around hypothesis testing: neither the null hypothesis nor an alternative hypothesis is ever "accepted"; instead, we "reject" or "fail to reject" a hypothesis.

Though standard, this terminology is somewhat overly restrictive. For one, you might wonder why rejecting one of two complementary hypotheses doesn't logically require us to accept the other. For another, we frequently behave *as if* we had accepted a given hypothesis (when was the last time you saw someone look up after they dropped something?), and so the utility of placing our language in a straitjacket that doesn't match practice is somewhat suspect, outside of highly technical discussion.
